---
- name: Stop and uninstall the service 
  command: "./svc.sh {{ cmd }}"
  loop:
    - stop
    - uninstall
  loop_control:
    loop_var: cmd
  args:
    chdir: "{{ vsts_agent_working_dir }}"
- name: Remove the service overlay directory 
  file:
    path: "/etc/systemd/system/{{ vsts_systemd_service_name }}.d"
    state: absent
- name: Unconfigure the existing agent
  command: "./config.sh remove --unattended --auth 'PAT' --token {{ vsts_agent_registration_token }}"
  become: true
  become_user: "{{ vsts_username }}"
  environment: "{{ vsts_agent_environment }}"
  ignore_errors: true
  args:
    chdir: "{{ vsts_agent_working_dir }}"
- name: Ensure the directory does not exist 
  file:
    path: "{{ vsts_agent_working_dir }}"
    state: absent