---
- name: Populate service facts
  ansible.builtin.service_facts:
- debug:
    msg: "{{ vsts_agents | default('bad') }}"
- name: Uninstall matching agents 
  include_tasks: pre-remove.yml
  loop: "{{ vsts_agents | default([]) }}"
  loop_control:
    loop_var: agent
- name: Find the latest release from Github API
  ansible.builtin.uri:
    url: https://api.github.com/repos/microsoft/azure-pipelines-agent/releases/latest
    return_content: yes
    headers:
      Accept: "application/vnd.github+json"
  register: latest_release
- set_fact:
    vsts_agent_release_tag: "{{ (latest_release.content | from_json)['tag_name'] }}"
- name: Setup agents 
  include_tasks: setup.yml
  loop: "{{ vsts_agents | default([]) }}"
  loop_control:
    loop_var: agent
  vars:
    vsts_agent_version: "{{ vsts_agent_release_tag | regex_replace('v') }}"
