---
- name: Populate service facts
  ansible.builtin.service_facts:
- debug:
    msg: "{{ ansible_facts.services.keys() | select('search','^vsts') | list }}"

- name: Match services running from that folder 
  shell: |
    cat $(systemctl show -P FragmentPath {{ svc }}) | grep ExecStart | cut -f 2 -d '=' | head -n 1 | xargs dirname
  loop: "{{ ansible_facts.services.keys() | select('search','^vsts') | list }}"
  loop_control:
    loop_var: svc
  register: _vsts_service_paths

- debug: 
    msg: "{{ _vsts_service_paths.results }}"

- ansible.builtin.set_fact:
    vsts_service_facts: "{{ (vsts_service_facts | default([])) + [{'value': svc, 'key': lookup('pipe','systemctl show -P FragmentPath ' + svc).split('')[1] | dirname}] }}"
  loop: "{{ (ansible_facts.services | dict2items | selectattr('key','search','^vsts') | list | items2dict).keys() }}"
  loop_control:
    loop_var: svc

- debug: 
    msg: "{{ vsts_service_facts }}"
- ansible.builtin.set_fact:
    vsts_service_facts: "{{ ansible_facts.services | dict2items | selectattr('key','search','^vsts') | list | items2dict }}"
- name: Match services running from that folder 
  shell: |
    cat $(systemctl show -P FragmentPath {{ svc }}) | grep ExecStart | cut -f 2 -d '=' | head -n 1 | xargs dirname
  loop: "{{ vsts_service_facts.keys() }}"
  loop_control:
    loop_var: svc
  register: vsts_service_home_folders

- debug:
    msg: "{{ vsts_service_home_folders }}"
- name: Uninstall matching agents 
  include_tasks: pre-remove.yml
  loop: "{{ vsts_agents | default([]) }}"
  loop_control:
    loop_var: agent
- name: Find the latest release from Github API
  ansible.builtin.uri:
    url: https://api.github.com/repos/microsoft/azure-pipelines-agent/releases/latest
    return_content: yes
    headers:
      Accept: "application/vnd.github+json"
  register: latest_release
- set_fact:
    vsts_agent_release_tag: "{{ (latest_release.content | from_json)['tag_name'] }}"
- name: Setup agents 
  include_tasks: setup.yml
  loop: "{{ vsts_agents | default([]) }}"
  loop_control:
    loop_var: agent
  vars:
    vsts_agent_version: "{{ vsts_agent_release_tag | regex_replace('v') }}"
