---
- set_fact:
    vsts_agent_working_dir: "{{ vsts_agent_base_folder }}/{{ agent.folder }}"
- name: Agent exists and needs to be uninstalled
  block:
    - name: Uninstall the agent 
      ansible.builtin.include_role:
        name: jamesjonesconsulting.azuredevops_agent_fixes.agent_remove
      vars:
        vsts_username: "{{ agent.username }}"
        vsts_systemd_service_name: "{{ vsts_service_home_folders.results | selectattr('stdout', 'equalto', vsts_agent_working_dir) | map(attribute='stdout') | flatten | list | first }}"
  when:
    - "vsts_service_home_folders.results | selectattr('stdout', 'equalto', vsts_agent_working_dir) | map(attribute='stdout') | flatten | list | count"
- name: Ensure the directory does not exist 
  file:
    path: "{{ vsts_agent_working_dir }}"
    state: absent