---
- name: Ensure overlay directories existing
  file:
    path: "/etc/systemd/system/{{ vsts_systemd_service_name }}.d"
    state: directory 
- name: Add overlays
  template:
    src: templates/overlay.conf.j2
    dest: "/etc/systemd/system/{{ vsts_systemd_service_name }}.d/overlay.conf"
- name: Perform a daemon-reload to pick up all the new overlays
  ansible.builtin.systemd:
    daemon_reload: yes
# - name: Restart all the VSTS agents
#   ansible.builtin.systemd:
#     name: "{{ vsts_systemd_service_name }}"
